### ISSUE TITLE
[1.15.2-forge] cant connect to server ,cant 2mill + fit into 3

### ISSUE THREAD

**Issue by SDUBZ** [Szewek/Flux#14]
flux-4.11.1
forge: 1.15.2
FL: fl-3.1.3

once i disabled these version i could get into server and didnt get the packet over size error

**Comment by SDUBZ** [comment]
http://puu.sh/Fn6wj/fa17783512.png

**Comment by Szewek** [comment]
This doesn't say very much. Please send `latest.log` file from client connecting to server with Flux. Server logs can also be helpful.

**Comment by Szewek** [comment]
Stale issue. Reopen if same thing happened.
