### ISSUE TITLE
Crashed when using flux power cable with mekanism.

### ISSUE THREAD

**Issue by IchigoGames** [Szewek/Flux#20]
- **Minecraft:** 1.15.2
- **Forge:**31.1.30
- **Flux:** flux-4.12.4

https://pastebin.com/jzGxCg37

**Steps to Reproduce:**
 1. ...connect any gen flux or other to a mek engery cube and transfer power use flux power cables
 2. ...then brake with a pick and crash

**Description of issue:**
reporting this to you and mek dev as i dont know whos issue it is but connecting mek to flux with flux cabbles crashed singeplayer and server only if using flux power cable.

**Comment by Szewek** [comment]
Even though Energy Cable is a ticking tile entity in this crash report, it is Mekanism fault.

**Source of this problem:** `LazyOptional` containing `ForgeEnergyIntegration` (from Mekanism) is not invalidated when Energy Cube is removed.

Flux removes invalid energy capabilities automatically, so no changes are needed here.

**Comment by Szewek** [comment]
I made a safety check to prevent crashes. It will be applied for Flux.
