### ISSUE TITLE
infinite coal dust

### ISSUE THREAD

**Issue by eloe79** [Szewek/Flux#21]
while using grinder, there is bug with infinite coal dust

**Versions:**
Minecraft Version: 1.15.2
Forge: net.minecraftforge: 31.1.35
flux-4.12.4.jar
[latest.log](https://github.com/Szewek/Flux/files/4430936/latest.log)

**Steps to Reproduce:**
 1. put stack of coal into grinder
 2. output [ i have used xnet, not sure if this matter ] to barrel

no issue as such, just infinite coal dust

**Comment by Szewek** [comment]
The fix was already done but it haven't been released yet (until now). Download [Flux Library 3.1.6](https://www.curseforge.com/minecraft/mc-mods/fl/files/2920848).
