### ISSUE TITLE
Mystical Agriculture seeds are getting duped when using the Farmer

### ISSUE THREAD

**Issue by extremMiSt** [Szewek/Flux#24]
**Versions:**
- **Minecraft:** 1.15.2
- **Forge:** 31.1.19
- **Flux Library:** 3.2.2
- **Flux:** 4.14.0
- **Mystical Agriculture:** 3.0.2
There is some "right click to harvest"-mod in this pack (Beyond Limits 1.15) , but I don't know which mod adds this functionality.

**Steps to Reproduce:**
 1. Plant Inferium Seeds
 2. Put down Farmer next to it
 3. Power the farmer
 4. Wait for plant to grow

**Description of issue:**
Expected result: 
Plant gets harvested, I get the drops from the plant (Inferium essence)
Actual result:
I additionally get the Seeds every time, with the plant still being planted (but growth stage reseted), thus duping the seed

**Comment by extremMiSt** [comment]
nope,

I still get a seed everytime a Mystical Agriculture plant gets harvested

**Comment by Szewek** [comment]
Currently Farmer checks if an item is registered in `forge:seeds` item tag before taking one item from a stack. It fixed issues with vanilla seeds. Mystical Agriculture has no seeds registered there and it's up to its developer to add approperiate items to this tag.

I will check on alternative solutions but I don't want to add specific code just for a singular mod to work properly (same code should work with all mods). 

Making a datapack with `data/forge/tags/items/seeds.json` with all item IDs of Mystical Agriculture seeds is the temporary solution.
```js
{
  "replace": false,
  "values": [
    // Add Mystical Agriculture seeds' item IDs here (remove comment first)
  ]
}
```
