### ISSUE TITLE
Flux-Engineer Trading with Ingots

### ISSUE THREAD

**Issue by papaworld** [Szewek/Flux#26]
Hello,
Trading with the Flux-Engineer only allows for "Flux" ingots (copper, tin, etc.)... using other mods in the game smelts copper into Mekanism, Silent Mechanisms and 8 others. The Flux-Engineer will not accept ingots from other mods. Would you change the trades to allow for anyCopper, anyTin, etc.
Really neat mod - Thank You.

MC: 1.15.2
FML: 31.2.0
FL: 3.2.2
Flux: 4.15.0

**Comment by Szewek** [comment]
That's a great idea, although it is harder to make. Generally each villager type has predefined trades that are created when villager spawns or gets a job. These trades are saved within villager's data. The "item equality" logic is in Minecraft code and normal mods can't modify it.

If there is a mod/library that customizes trades then I will look into this.

**Comment by papaworld** [comment]
Hi again.
Did a workaround with the ingot issue with the Flux Engineer. Used Mekanism OreDictionificator to change copper and tin ingots to Flux mod type.

But now having a bit of problems after updating MC to the following:
MC: 1.15.2
FML: 31.2.5
FL: 3.3.0
Flux: 4.16.1

The Copper and Tin Ingot no longer appear in JEI. Also, the Flux Chip has disappeared too. Seems all the machines, tools, ore, metal blocks are still there. I can get the ingots from the Mekanism OreDictionificator.

Again... great mod! The Online Market is super!
