### ISSUE TITLE
Unreadable Flux Book

### ISSUE THREAD

**Issue by an-amoeba** [Szewek/Flux#27]
![Captura de pantalla 2020-05-24 a la(s) 3 40 04 p  m](https://user-images.githubusercontent.com/65869724/82763395-55205a80-9dd5-11ea-87b6-563de2d320c5.png)
**Versions:**
- **Minecraft:** 1.15.2
- **Forge:** 31.1.77
- **Flux Library:** 3.2.2
- **Flux:** 4.14.0

**Steps to Reproduce:**
 1. Interact with Flux Book

**Description of issue:**
I'm not able to read the Flux Book because the text appears as rectangles. I've attached a screenshot of the text.

**Comment by Szewek** [comment]
This problem is already described in Patchouli (Flux Book is created by this mod). See Vazkii/Patchouli#236 for details.
