### ISSUE TITLE
[1.15.2] Crash with world start

### ISSUE THREAD

**Issue by IchigoGames** [Szewek/Flux#28]
**Versions:**
- **Minecraft:**1.15.2
- **Forge:** 31.2.0
- **Flux Library:**fl-3.3.0 
- **Flux:**flux-4.16.0

crash report https://pastebin.com/SaJS9w2q

**Steps to Reproduce:**
 1. ...updated flux
 2. ...loaded into singeplayer it my modpack and crashed

**Description of issue:**
this one took a long time to find out what was doing it the crash was not much help so i un did my update a mod or two at a time till it stopped crashing and they stopped when i removed flux with flux it crashed without flux it did not crash fl core is not a issue tested with out flux and it did not crash of course i cant test if flux crashed without fl core as it needs it but it does crash with both. let me know if you need anymore info

edit the modpack is https://www.curseforge.com/minecraft/modpacks/the-endless-frontier working on a update so version not out yet.

**Comment by Szewek** [comment]
This problem comes from JAOPCA failing at creating Flux recipes. I made a temporary fix to prevent Minecraft from crashing.
