### ISSUE TITLE
Crash when trying to start the server

### ISSUE THREAD

**Issue by k4mix** [Szewek/Flux#4]
This crash appears when i'am starting server 
first i tried with few mods but after first crash I just left only your mod , and the same crash appears
crash report
[crash-2020-01-30_22.00.54-server.txt](https://github.com/Szewek/Flux/files/4136257/crash-2020-01-30_22.00.54-server.txt)
logs
[latest.log](https://github.com/Szewek/Flux/files/4136258/latest.log)

**Comment by Szewek** [comment]
Necessary fix is coming. This error also appears in Flux versions before 4.4.1.
