### ISSUE TITLE
possible mod compat issue

### ISSUE THREAD

**Issue by christomite** [Szewek/Flux#62]
**Versions:**
- **Minecraft:** 1.16.5
- **Forge:** 36.0.1
- **Flux Library:** 4.3.1
- **Flux:** {5.3.3

**Logs:** no crash just an issue with compat with another mod https://www.curseforge.com/minecraft/mc-mods/auto-ore-dictionary-converter#c72 
im gooberbomb1 one our convo is there with issue

**Steps to Reproduce:**
 1. installed just your mod mekanism and autooredicconvert 
 2. with your mod installed and i use the odc/ add command with your mod installed it adds this line to his conversion
 3. flux:market_accept=mekanism:ingot_copper

when i try to convert the mekanism copper using his command your mod adds that line to his conversion table which then makes al ores eg iron lead anything turn to copper

**Comment by Szewek** [comment]
Technically `flux:market_accept` tag works like `minecraft:piglin_loved` (this is for items admired by Piglin). It is not used for recipes at all (and it should not be). By default all ingots are there so Online Market can fix trading ingots from different mods.

Maybe AODC mod developer overlooked these types of tag usages and focused on basic tag conversion. It just so happens that this mod has a [tag blacklist written in the code](https://github.com/MattDahEpic/AutoOreDictConvert/blob/1.16.X/src/main/java/com/mattdahepic/autooredictconv/common/convert/Conversions.java#L19). Adding `"flux:market_accept"` here might fix this problem.
